In [4]:
import numpy as np

array = np.random.randint(1, 51, size=(3, 4))

mean = np.mean(array)
median = np.median(array)
std = np.std(array)

total = np.sum(array)
row_sum = np.sum(array, axis=1)

new = array.reshape(2, 6)

print(" ORGINAL ARRAY:")
print(array)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Sum of all elements:", total)
print("Sum of each row:", row_sum)
print("NEW ARRAY  (2x6):")
print(new)


 ORGINAL ARRAY:
[[10  1 38 14]
 [49 50  3 27]
 [ 8 24 41 44]]

Mean: 25.75
Median: 25.5
Standard Deviation: 17.512495538900218
Sum of all elements: 309
Sum of each row: [ 63 129 117]
NEW ARRAY  (2x6):
[[10  1 38 14 49 50]
 [ 3 27  8 24 41 44]]


In [16]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

add = matrix1 + matrix2
print("Matrix Addition:")
print(add)

sub= matrix1 - matrix2
print("b.Matrix Subtraction:")
print(sub)

mul = matrix1 * matrix2
dot = np.dot(matrix1, matrix2)
print("Matrix Multiplication:")
print(dot)

transpose1 = np.transpose(matrix1)
transpose2 = np.transpose(matrix2)
print("Transpose of Matrix 1:")
print(transpose1)
print("Transpose of Matrix 2:")
print(transpose2)

det1 = int(np.linalg.det(matrix1))
det2 = int(np.linalg.det(matrix2))
print(f"Determinant of Matrix 1: {det1}")
print(f"Determinant of Matrix 2: {det2}")

# Check if matrices are invertible (determinant != 0)
if det1 != 0:
    inv1 = np.linalg.inv(matrix1)
    print(int(inv1))
else:
    print("Matrix 1 is not invertible")
if det2 != 0:
    inv2 = np.linalg.inv(int(matrix2))
    print(inv2)
else:
    print("Matrix 2 is not invertible")


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
b.Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of Matrix 1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Matrix 2:
[[9 6 3]
 [8 5 2]
 [7 4 1]]
Determinant of Matrix 1: 0
Determinant of Matrix 2: 0
Matrix 1 is not invertible
Matrix 2 is not invertible
